### ISSUE TITLE
Some person life exp.

### ISSUE THREAD

**Issue by stosSe4r** [Problem233/blog#1]
Hi pr. I've read your solution to TCOC003.
Honestly, this program's complexity is too high...wwww  It's needless to argue that using struct. is a kind of waste wwwwwwww
Oh, the way u use the sort function is ugly..The comparing function needs independence! (XD) U may make it a individual func.
The loop u write is Eye-breakive233 
I think the cpp code u write is based on func. idea......
In the other hand, scala ver. is much betterrrr wwwwwwww
Just some small contribution, thank everyone-

**Comment by refparo** [comment]
23333
