### ISSUE TITLE
About comment system and loading speed

### ISSUE THREAD

**Issue by swwind** [problem233/blog#8]
For comment system, I think use github issues directly is not a good resolution for static websites. Valine, Gitalk and Gitment are all popular comment systems designed for static websites. Maybe you should have a look on them.

As for sped-up loading speed, Aliyun is what I recommended. They sale their cloud server with only 10CNY per month and with nice equipment and network speed(40G SSD, 2G RAM, 2T bandwidth, 13ms ping). The only limitation is that it is only for students under 24 yrs old as an educational aid project. I have tried it and find they blocked my 80 port for some reason but 443 port is still available to set up a HTTPS server. Now I have been using it as a blog host or even as a Minecraft server for several month with no troubles take place. As you can see, github pages is getting slower in speed. If you do not want to buy a server, Netlify is also recommend at least it is faster than github pages.

Just suggestions. (=・ω・=) :heart:

**Comment by swwind** [comment]
I want to f**k Aliyun now.
They blocked my 443 port and I have to buy a HK server with much higher price...

**Comment by problem233** [comment]
你需要备案（
